apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tunnel-token
  namespace: cloudflare
  labels:
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/part-of: sagelms
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm-sagelms-devsecops
  target:
    name: tunnel-token
    creationPolicy: Owner
  data:
    - secretKey: TUNNEL_TOKEN
      remoteRef:
        key: sagelms-devsecops-cloudflared-tunnel-token
