apiVersion: v1
kind: Namespace
metadata:
  name: sagelms-devsecops
  labels:
    app.kubernetes.io/part-of: sagelms
    sagelms.io/environment: devsecops
---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
  labels:
    app.kubernetes.io/part-of: sagelms
    sagelms.io/environment: devsecops
---
apiVersion: v1
kind: Namespace
metadata:
  name: sagelms-data
  labels:
    app.kubernetes.io/part-of: sagelms
    sagelms.io/environment: devsecops
