apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-shared-secret
  labels:
    app.kubernetes.io/name: app-shared-secret
    app.kubernetes.io/part-of: sagelms
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm-sagelms-devsecops
  target:
    name: app-shared-secret
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: sagelms-devsecops-jwt-secret
    - secretKey: GATEWAY_SHARED_SECRET
      remoteRef:
        key: sagelms-devsecops-gateway-shared-secret
    - secretKey: INTERNAL_API_SECRET
      remoteRef:
        key: sagelms-devsecops-internal-api-secret
