apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-pull-secret
  namespace: sagelms-devsecops
  labels:
    app.kubernetes.io/name: harbor-pull-secret
    app.kubernetes.io/part-of: sagelms
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm-sagelms-devsecops
  target:
    name: harbor-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: sagelms-devsecops-harbor-pull-secret
