apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
  labels:
    app.kubernetes.io/name: worker
    app.kubernetes.io/part-of: sagelms
data:
  SPRING_PROFILES_ACTIVE: "gke"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
