apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: sagelms
data:
  SERVER_PORT: "8080"
  SPRING_PROFILES_ACTIVE: "gke"
  AUTH_SERVICE_HOST: "auth-service"
  AUTH_SERVICE_PORT: "8081"
  COURSE_SERVICE_HOST: "course-service"
  COURSE_SERVICE_PORT: "8082"
  CONTENT_SERVICE_HOST: "content-service"
  CONTENT_SERVICE_PORT: "8083"
  PROGRESS_SERVICE_HOST: "progress-service"
  PROGRESS_SERVICE_PORT: "8084"
  ASSESSMENT_SERVICE_HOST: "assessment-service"
  ASSESSMENT_SERVICE_PORT: "8085"
