apiVersion: v1
kind: Service
metadata:
  name: assessment-service
  labels:
    app.kubernetes.io/name: assessment-service
    app.kubernetes.io/part-of: sagelms
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: assessment-service
  ports:
    - name: http
      port: 8085
      targetPort: http
