apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: sagelms-postgres-backup-store
  namespace: sagelms-data
  labels:
    app.kubernetes.io/name: sagelms-postgres
    app.kubernetes.io/part-of: sagelms
spec:
  configuration:
    destinationPath: gs://sagelms-cnpg-backup-sagelms/sagelms-postgres
    googleCredentials:
      gkeEnvironment: true
    wal:
      compression: gzip
    data:
      compression: gzip
  retentionPolicy: "30d"
