apiVersion: v1
kind: ServiceAccount
metadata:
  name: harbor-registry
  namespace: harbor
  annotations:
    iam.gke.io/gcp-service-account: sagelms-devsecops-harbor-gcs@sagelms.iam.gserviceaccount.com
  labels:
    app.kubernetes.io/name: harbor-registry
    app.kubernetes.io/part-of: sagelms
    sagelms.io/component: registry-storage