apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: harbor
  namespace: harbor
  labels:
    app.kubernetes.io/name: harbor
    app.kubernetes.io/part-of: sagelms
spec:
  interval: 1h
  url: https://helm.goharbor.io
