apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sagelms-devsecops

resources:
  - ../../base/apps
  - app-shared-externalsecret.yaml
  - ingress.yaml

images:
  - name: harbor.sagelms.dev/sagelms-app/gateway
    newName: asia-southeast1-docker.pkg.dev/sagelms/sagelms-app/gateway
    newTag: gke-temp-93d7c34
  - name: harbor.sagelms.dev/sagelms-app/auth-service
    newName: asia-southeast1-docker.pkg.dev/sagelms/sagelms-app/auth-service
    newTag: gke-temp-93d7c34
  - name: harbor.sagelms.dev/sagelms-app/course-service
    newName: asia-southeast1-docker.pkg.dev/sagelms/sagelms-app/course-service
    newTag: gke-temp-93d7c34
  - name: harbor.sagelms.dev/sagelms-app/content-service
    newName: asia-southeast1-docker.pkg.dev/sagelms/sagelms-app/content-service
    newTag: gke-temp-93d7c34
  - name: harbor.sagelms.dev/sagelms-app/progress-service
    newName: asia-southeast1-docker.pkg.dev/sagelms/sagelms-app/progress-service
    newTag: gke-temp-93d7c34
  - name: harbor.sagelms.dev/sagelms-app/assessment-service
    newName: asia-southeast1-docker.pkg.dev/sagelms/sagelms-app/assessment-service
    newTag: gke-temp-93d7c34
  - name: harbor.sagelms.dev/sagelms-app/web
    newName: asia-southeast1-docker.pkg.dev/sagelms/sagelms-app/web
    newTag: gke-temp-93d7c34

patches:
  - target:
      kind: Service
      name: gateway
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          cloud.google.com/neg: '{"ingress": true}'
  - target:
      kind: Service
      name: web
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          cloud.google.com/neg: '{"ingress": true}'
  - target:
      kind: ServiceAccount
      name: worker
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: worker
  - target:
      kind: ConfigMap
      name: worker-config
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: worker-config
  - target:
      kind: Deployment
      name: worker
    patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: worker
